VERSION:=0.1

all: makedist

makedist: clean
	tar czvf cuda_emicp_softassign.$(VERSION).tar.gz CUDA_EMICP_SOFTASSIGN.* README.txt Makefile* src/*.{cpp,h,c,cu} src/{Makefile,CUDA_EMICP_SOFTASSIGN} data/ win/ --exclude=.svn
	
	
clean:
	rm -f cuda_emicp_softassign.$(VERSION).tar.gz
	